### PR TITLE
[Fix] Proper dot-annotation support for `ValueMap#remove(name)`

### PR DESCRIPTION
**Pull request by CDAGaming**
- References how `.set` works
- Needs review over behavior when `value` is not a map

### CODE REVIEW

**Comment by CDAGaming** [comment]
CC @MineGame159 for review

**Comment by MineGame159** [comment]
Looks good but apart from one thing. Looks like you made it return `this` but in the context of a `remove()` method I would expect it to return the removed object or null if it couldnt remove anything. Any reason why you decided like this? Also the return value should be documented in javadoc.

**Comment by CDAGaming** [comment]
As mentioned it was mostly based on how set was written so there isnt a need to have it return anything. In this case though, I can probably swap the fail cases to return null

**Comment by CDAGaming** [comment]
As for the return value, again note the documentation was based on set which also doesnt document an @return value

**Pull request merged**
